info:
  app:
    name: @project.artifactId@
    description: @project.description@
    version: @project.version@

spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
  mvc:
    view:
       suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: select 1
  mail:
    host: smtp.qq.com  # qq  smtp服务器地址
    username: 1352029800@qq.com
    password: klyyylgbilyvbadj             #rhhd nccd yngs gadf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jasypt:
  encryptor:
    password: ${app-secret:ecudowid}


mybatis:
  type-aliases-package: com.njit.stusystem.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    database-id: mysql
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


pagehelper:
  helperDialect: mysql
  reasonable: true
  pageSizeZero: true



